# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: f114deafa2adf8ddf6bb4a87ead45ca1497a594e94eebb5682cb0787a5f6140b32850d2482bb8bf57696272fefe9129134796ab2eb95c1d0158327182f60cdd9

test:
  secret_key_base: 1f9086329a61d674b614350f895960a2c9b55a97075fb2ed46987350b5647786c118e2f127cf5263fe83b2eb7c9cdbd62223390c10c178e016ed8531e251dd7a

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
